version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dagster_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dagster_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - postgres_data:/var/lib/postgresql/data

  dagster:
    build: .
    container_name: dagster_pipeline
    working_dir: /app
    environment:
      DAGSTER_HOME: /app/dagster_home
    ports:
      - "3001:3000"
    volumes:
      - ./dagster_home:/app/dagster_home
      - ./data:/app/data  # Mount directly under /app
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:

      - postgres

volumes:
  postgres_data:
  pgadmin_data:
